Fixup 6.x->417
Because we were getting:
```
Download of Microsoft.Extensions.DependencyInjection 5.0.1 done in 161 milliseconds. (9235 kbit/s, 0 MB)
Starting task 'DotNet:version': running dotnet --version
6.0.417
Finished (Success) 'DotNet:version' in 00:00:00.3822090
Script is not valid:
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (82,60)-(82,66): Error FS0039: The value, namespace, type or module 'SemVer' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (84,28)-(84,33): Error FS0039: The record label 'Patch' is not defined.
Hint: If you have updated your dependencies you might need to run 'paket install' or delete '/home/runner/work/FSharpLint/FSharpLint/build.fsx.lock' for fake to pick them
up.
Hint: If this doesn't help but you are sure this should work try to clean your nuget cache and delete the .fake directory. If this helps please report this problem to Paket.
Hint: Detected paket version '7.2.1' in your paket.dependencies file bootstrapper arguments, consider locking the version to '7.1.5' in your dependencies file
(/home/runner/work/FSharpLint/FSharpLint/paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
Error: Process completed with exit code 1.
```