paket.lock: update FAKE to v6
With `dotnet paket update --group build`, because we were getting:
```
Script is not valid:
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (82,60)-(82,66): Error FS0039: The value, namespace, type or module 'SemVer' is not defined.
	/home/runner/work/FSharpLint/FSharpLint/build.fsx (84,28)-(84,33): Error FS0039: The record label 'Patch' is not defined.
Hint: If you have updated your dependencies you might need to run 'paket install' or delete '/home/runner/work/FSharpLint/FSharpLint/build.fsx.lock' for fake to pick them up.
Hint: If this doesn't help but you are sure this should work try to clean your nuget cache and delete the .fake directory. If this helps please report this problem to Paket.
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
Performance:
 - Cli parsing: 223 milliseconds
 - Packages: 9 seconds
   - Disk IO: 6 seconds
   - Average Download Time: 19 milliseconds
   - Number of downloads: 184
   - Average Request Time: 18 milliseconds
   - Number of Requests: 219
   - Creating Runtime Graph: 43 milliseconds
   - Retrieve Assembly List: 2 seconds
 - Script compiling: 2 seconds
 - Script analyzing: 159 milliseconds
 - Runtime: 14 seconds
Error: Process completed with exit code 1.
```