paket.dependencies: pin MS.NET.Test.Sdk to higher version
In order to avoid this problem when running the tests:
```
Starting task 'DotNet:test': tests/FSharpLint.FunctionalTest
/home/runner/work/FSharpLint/FSharpLint> "/usr/share/dotnet/dotnet"  test tests/FSharpLint.FunctionalTest --filter "\"TestCategory!=Performance\"" --configuration Release /clp:ForceConsoleColor /bl:/tmp/tmpiSN5Sm.tmp.binlog (In: false, Out: false, Err: false)
/usr/share/dotnet/sdk/6.0.417/MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/share/dotnet/sdk/6.0.417/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/share/dotnet/sdk/6.0.417/dotnet.dll -maxcpucount -nodereuse:false -property:VSTestTestCaseFilter=TestCategory!=Performance -property:Configuration=Release -restore -target:VSTest -verbosity:m /bl:/tmp/tmpiSN5Sm.tmp.binlog /clp:ForceConsoleColor tests/FSharpLint.FunctionalTest/FSharpLint.FunctionalTest.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  FSharpLint.Core -> /home/runner/work/FSharpLint/FSharpLint/src/FSharpLint.Core/bin/Release/net6.0/FSharpLint.Core.dll
  FSharpLint.FunctionalTest -> /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest/bin/Release/net6.0/FSharpLint.FunctionalTest.dll
Test run for /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest/bin/Release/net6.0/FSharpLint.FunctionalTest.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.3.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Lint multi-targeted project [723 ms]
  Error Message:
     MSBuildFailedToLoadProjectFile
  ("/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj",
   InvalidProjectFileMessage
     "GenericError
  ("/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj",
   "Build started.
Project "FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj" (ResolvePackageDependenciesDesignTime;_GenerateCompileDependencyCache;CoreCompile target(s)):
Target "_CheckForUnsupportedTargetFramework" skipped, due to false condition; ('$(_UnsupportedTargetFrameworkError)' == 'true') was evaluated as ('' == 'true').
Target "_CollectTargetFrameworkForTelemetry" in file "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets" from project "/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj" (target "RunResolvePackageDependencies" depends on it):
Using "AllowEmptyTelemetry" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
Task "AllowEmptyTelemetry"
Done executing task "AllowEmptyTelemetry".
Done building target "_CollectTargetFrameworkForTelemetry" in project "FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj".
Target "_CheckForUnsupportedTargetPlatformIdentifier" skipped, due to false condition; ('$(TargetPlatformIdentifier)' != '' and '$(TargetFrameworkIdentifier)' == '.NETCoreApp' and $([MSBuild]::VersionGreaterThanOrEquals($(TargetFrameworkVersion), 5.0)) And ('$(DesignTimeBuild)' != 'true' Or '@(MissingWorkloadPack)' == '')) was evaluated as ('Windows' != '' and '.NETCoreApp' == '.NETCoreApp' and False And ('true' != 'true' Or '' == '')).
Target "_CheckForMissingWorkload" skipped, due to false condition; ('@(MissingWorkloadPack)' != '' And '$(DesignTimeBuild)' != 'true') was evaluated as ('' != '' And 'true' != 'true').
Target "RunResolvePackageDependencies" in file "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets" from project "/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj" (target "ResolvePackageDependenciesDesignTime" depends on it):
Task "CheckForTargetInAssetsFile" skipped, due to false condition; ( '$(DesignTimeBuild)' != 'true') was evaluated as ( 'true' != 'true').
Using "ResolvePackageDependencies" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
Task "ResolvePackageDependencies"
Error reading assets file: Error loading lock file '/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/obj/project.assets.json' : Error reading '' at line 31 column 22 : Could not load type 'NuGet.Frameworks.DualCompatibilityFramework' from assembly 'NuGet.Frameworks, Version=5.0.0.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
Build continuing because "ContinueOnError" on the task "ResolvePackageDependencies" is set to "ErrorAndContinue".
Done executing task "ResolvePackageDependencies" -- FAILED.
Done building target "RunResolvePackageDependencies" in project "FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj" -- FAILED.
Target "AssignProjectConfiguration" skipped, due to false condition; ('$(CurrentSolutionConfigurationContents)' != '' or '@(ProjectReference)'!='') was evaluated as ('' != '' or ''!='').
Target "AddWindowsSdkKnownFrameworkReferences" in file "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets" from project "/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj" (target "ProcessFrameworkReferences" depends on it):
Using "CreateWindowsSdkKnownFrameworkReferences" task from assembly "/usr/share/dotnet/sdk/6.0.417/Sdks/Microsoft.NET.Sdk/targets/../tools/net6.0/Microsoft.NET.Build.Tasks.dll".
  Expected: True
  But was:  False

  Stack Trace:
     at FSharpLint.FunctionalTest.TestApi.TestApi.Lint solution via relative path() in /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest/TestApi.fs:line 148

  Failed FunctionalTestConsoleApplication [649 ms]
  Error Message:
     Did not find the following expected errors: [`List.fold ( + ) 0 x` might be able to be refactored into `List.sum x`.,`List.head (List.sort x)` might be able to be refactored into `List.min x`.,`a <> true` might be able to be refactored into `not a`.,`fun x -> x` might be able to be refactored into `id`.,`not (a <> b)` might be able to be refactored into `a = b`.,`not (a = b)` might be able to be refactored into `a <> b`.,`not false` might be able to be refactored into `true`.,`not true` might be able to be refactored into `false`.,`x = null` might be able to be refactored into `isNull x`.]
Found the following unexpected warnings: []
Complete output: MSBuild could not load the project file /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj because: InvalidProjectFileMessage
  "GenericError
  ("/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.NetCore/FSharpLint.FunctionalTest.TestedProject.NetCore.fsproj",
   "Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)")"

  Expected and actual are both <Microsoft.FSharp.Collections.FSharpSet`1[System.String]>
  Values differ at index [0]
  Missing:  < "`List.fold ( + ) 0 x` might be able to be refactored into `List.sum x`.", ... >
  Stack Trace:
     at FSharpLint.FunctionalTest.Tests.TestConsoleApplication.FunctionalTestConsoleApplication() in /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest/TestConsoleApplication.fs:line 108

  Failed FunctionalTestConsoleApplicationSolution [628 ms]
  Error Message:
     Did not find the following expected errors: [`List.fold ( + ) 0 x` might be able to be refactored into `List.sum x`.,`List.head (List.sort x)` might be able to be refactored into `List.min x`.,`a <> true` might be able to be refactored into `not a`.,`fun x -> x` might be able to be refactored into `id`.,`not (a <> b)` might be able to be refactored into `a = b`.,`not (a = b)` might be able to be refactored into `a <> b`.,`not false` might be able to be refactored into `true`.,`not true` might be able to be refactored into `false`.,`x = null` might be able to be refactored into `isNull x`.]
Found the following unexpected warnings: []
Complete output: MSBuild could not load the project file /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj because: InvalidProjectFileMessage
  "GenericError
  ("/home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest.TestedProject/FSharpLint.FunctionalTest.TestedProject.MultiTarget/FSharpLint.FunctionalTest.TestedProject.MultiTarget.fsproj",
   "Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)")"

  Expected and actual are both <Microsoft.FSharp.Collections.FSharpSet`1[System.String]>
  Values differ at index [0]
  Missing:  < "`List.fold ( + ) 0 x` might be able to be refactored into `List.sum x`.", ... >
  Stack Trace:
     at FSharpLint.FunctionalTest.Tests.TestConsoleApplication.FunctionalTestConsoleApplicationSolution() in /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest/TestConsoleApplication.fs:line 124


Failed!  - Failed:     8, Passed:     2, Skipped:     0, Total:    10, Duration: 3 s - /home/runner/work/FSharpLint/FSharpLint/tests/FSharpLint.FunctionalTest/bin/Release/net6.0/FSharpLint.FunctionalTest.dll (net6.0)
Finished (Failed) 'DotNet:test' in 00:00:06.3834118
Finished (Failed) 'Test' in 00:01:17.1570330

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0006282
Build      00:00:21.5764402
Test       00:01:17.1569352   (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
Total:     00:01:38.7763107
Status:    Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Test' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
Error: Process completed with exit code 1.
```