scripts: convert `BuildRelease` FAKE target to fsx
The 'Docs' target is dependent on the 'BuildRelease' target
therefore it remains in build.fsx. It should only be removed
after the `Docs` target has been converted. Removing it will
lead to the error detailed below:

```
run Docs
Building project with version: 1282
Shortened DependencyGraph for Target Docs:
<== Docs
   <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - Docs
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0027457
Starting target 'Docs'
docs> "dotnet" fornax build (In: false, Out: false, Err: false)
System.Exception: Unknown project name. Provide 'properties' parameter with 'project-name' key.
   at FSharp.MetadataFormat.MetadataFormat.Generate(IEnumerable`1 dllFiles, FSharpOption`1 parameters, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownComments, FSharpOption`1 urlRangeHighlight) in /app/src/FSharp.MetadataFormat/Main.fs:line 1616
   at FSI_0016.Apirefloader.loader(String projectRoot, SiteContents siteContet)
[09:13:22] multiple files generated in 879ms
[09:13:23] '/home/runner/work/FSharpLint/FSharpLint/docs/_public/index.json' generated in 187ms
An unexpected error happend: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Generator.EvaluatorHelpers.helper@54(Object next, FSharpList`1 args) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 64
   at Generator.EvaluatorHelpers.invokeFunction(Object f, IEnumerable`1 args) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 68
   at Generator.GeneratorEvaluator.evaluate@175-1.Invoke(FsiValue ft) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 178
   at Microsoft.FSharp.Core.ResultModule.Bind[T,TResult,TError](FSharpFunc`2 binder, FSharpResult`2 result) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\result.fs:line 15
   at Generator.GeneratorEvaluator.evaluate(FsiEvaluationSession fsi, SiteContents siteContent, String generatorPath, String projectRoot, String page) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 175
   at Generator.generate(FsiEvaluationSession fsi, Config cfg, SiteContents siteContent, String projectRoot, String page) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 321
   at Generator.action@1(String projectRoot, FsiEvaluationSession fsi, Config config, SiteContents sc, String filePath) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 479
   at Generator.generateFolder(String projectRoot, Boolean isWatch) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Generator.fs:line 478
   at Fornax.main$cont@123(ArgumentParser`1 parser, FSharpList`1 results, Unit unitVar) in D:\Programowanie\Projekty\Ionide\Fornax\src\Fornax\Fornax.fs:line 156
Finished (Failed) 'Docs' in 00:00:07.2170353
```

Co-authored-by: webwarrior <reg@webwarrior.ws>